import { Router } from 'express';
import { memoryRouter } from './memory';
import { settingsRouter } from './settings';
import { chatRouter } from './chat';
import { actionsRouter } from './actions';
import { x402Router } from './x402';
import { workflowsRouter } from './workflows';
import { portfolioRouter } from './portfolio';
import { approvalsRouter } from './approvals';
import { protocolsRouter } from './protocols';
import { statusRouter } from './status';
import { marketRouter } from './market';
import { autonomyRouter } from './autonomy';
import { mcpBaseRouter } from './mcpBase';
import { authRouter } from './auth';
import { routeIntelligenceRouter } from './routeIntelligence';
import { enforceTenantBinding, requireTenant } from '../middleware/tenantAuth';

export const routes = Router();

routes.use('/auth', authRouter);
routes.use(requireTenant, enforceTenantBinding);
routes.use('/memory', memoryRouter);
routes.use('/settings', settingsRouter);
routes.use('/chat', chatRouter);
routes.use('/actions', actionsRouter);
routes.use('/x402', x402Router);
routes.use('/workflows', workflowsRouter);
routes.use('/portfolio', portfolioRouter);
routes.use('/approvals', approvalsRouter);
routes.use('/protocols', protocolsRouter);
routes.use('/status', statusRouter);
routes.use('/market', marketRouter);
routes.use('/autonomy', autonomyRouter);
routes.use('/mcp/base', mcpBaseRouter);
routes.use('/route-intelligence', routeIntelligenceRouter);
