import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'readonly',
        process: 'readonly',
        console: 'readonly',
        exports: 'readonly',
        setTimeout: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-require-imports': 'off',
      'no-prototype-builtins': 'off',
    },
  },
  {
    // Generated/built artifacts only — real source stays linted.
    ignores: [
      'node_modules',
      '**/dist/**',
      'build',
      'coverage',
      '**/.next/**',
      // Generated by `next build` and git-ignored; Next 15.5 emits a
      // triple-slash reference to ./.next/types/routes.d.ts that the TS rules
      // reject. The file carries its own "should not be edited" notice, so
      // there is nothing to fix in it.
      '**/next-env.d.ts',
      'contracts/lib/**',
      'contracts/out/**',
      'contracts/cache/**',
    ],
  },
);
