import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'readonly',
        process: 'readonly',
        console: 'readonly',
        exports: 'readonly',
        setTimeout: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      // `ignoreRestSiblings` is not a relaxation: every hash in this codebase is
      // recomputed by omitting the old one — `const { chargeHash: _chargeHash,
      // ...rest } = charge` — and the named binding exists only so the rest
      // spread drops that key. Reporting it asks for the idiom to be rewritten
      // into something less clear.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-require-imports': 'off',
      'no-prototype-builtins': 'off',
    },
  },
  {
    // The manual launch check runs in a browser devtools console, not in Node.
    // Linted rather than ignored — it is the one script a person is invited to
    // paste into a page holding their session, so it should stay under review.
    files: ['scripts/manual-phase15-auth-smoke.js'],
    languageOptions: {
      globals: {
        fetch: 'readonly',
        performance: 'readonly',
        URLSearchParams: 'readonly',
        // devtools-only: it copies the result to the clipboard, and the call
        // is already wrapped in a try/catch for hosts that do not provide it.
        copy: 'readonly',
      },
    },
  },
  {
    // Generated/built artifacts only — real source stays linted.
    ignores: [
      'node_modules',
      '**/dist/**',
      'build',
      'coverage',
      '**/.next/**',
      // Generated by `next build` and git-ignored; Next 15.5 emits a
      // triple-slash reference to ./.next/types/routes.d.ts that the TS rules
      // reject. The file carries its own "should not be edited" notice, so
      // there is nothing to fix in it.
      '**/next-env.d.ts',
      'contracts/lib/**',
      'contracts/out/**',
      'contracts/cache/**',
      // `tsc -b` emits compiled JS beside the TypeScript it came from, and
      // those files are git-ignored build output. Linting them turned a clean
      // gate into six `no-undef` errors purely because the build had run
      // first -- `pnpm lint` passed or failed depending on what ran before it.
      'lib/*/src/**/*.js',
      'lib/*/test/**/*.js',
    ],
  },
);
