-- Call the reopen: a number for every player, and what the notifier told whom.
--
-- ONE: A PLAYER NUMBER
--
-- The leaderboard names a player by their Basename when their wallet has one,
-- and otherwise as "Player 12". A number in the order players joined, rather
-- than a tag cut from a hash: a tag derived from an address can be recomputed
-- by anybody holding a list of addresses, and that would say which of them
-- play here. Existing players are numbered when the column is added.
--
-- TWO: THE ROUND'S NOTICES
--
-- Three pushes per round: the invitation once it opens, a last call before
-- the lock for players who have not picked, and the results. Each goes to a
-- wallet once per channel, and this table is how a pass that runs every five
-- minutes knows it already went.
--
-- Applied by the deploy, as the app user, inside the migrator's own
-- transaction. Re-runnable.
ALTER TABLE reopen_players ADD COLUMN IF NOT EXISTS player_number bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS reopen_players_number_idx ON reopen_players (player_number);
CREATE TABLE IF NOT EXISTS reopen_notices (
  channel text NOT NULL CHECK (channel IN ('base_app', 'telegram')),
  round_id text NOT NULL REFERENCES reopen_rounds(round_id),
  kind text NOT NULL CHECK (kind IN ('open', 'last_call', 'results')),
  wallet_address text NOT NULL CHECK (wallet_address ~ '^0x[0-9a-f]{40}$'),
  sent_at timestamptz NOT NULL,
  PRIMARY KEY (channel, round_id, kind, wallet_address)
);
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'miorail_user') THEN
    ALTER TABLE reopen_notices OWNER TO miorail_user;
  END IF;
END $$;
