// GENERATED by scripts/refreshBaseMcpPluginHosts.mts — do not edit by hand.
//
// The hosts each native Base MCP plugin reaches, taken from the specs Base
// publishes at github.com/base/skills. These are the same files Claude and
// ChatGPT load, so this list is exactly what those clients can reach.
//
// Committed rather than fetched: an allowlist that refreshes itself from the
// network is one nobody reviews, and an outage at the source would silently
// empty or widen it. Every change to this file arrives in a diff.
//
// Regenerated 2026-08-09.

export const BASE_MCP_PLUGIN_HOSTS_V1: Readonly<Record<string, readonly string[]>> = {
  'aerodrome': ['base-rpc.publicnode.com'],
  'avantis': ['api.avantisfi.com', 'core.avantisfi.com', 'data.avantisfi.com', 'tx-builder.avantisfi.com', 'www.avantisfi.com'],
  'balancer': ['api-v3.balancer.fi', 'balancer.fi', 'test-api-v3.balancer.fi'],
  'bankr': ['api.bankr.bot', 'bankr.bot'],
  'bitrefill': ['api.bitrefill.com', 'www.bitrefill.com'],
  'brickken': ['mcp.brickken.com'],
  'clawnch': ['clanker.world', 'www.clawn.ch'],
  'flaunch': ['i.flaunch.gg', 'mcp.flaunch.gg'],
  'gmgn': ['openapi.gmgn.ai'],
  'hydrex': ['hydrex-agent.com', 'hydrex.fi'],
  'kyberswap': ['aggregator-api.kyberswap.com', 'token-api.kyberswap.com'],
  'moonwell': ['api.moonwell.fi'],
  'morpho': ['mcp.morpho.org'],
  'o1-exchange': ['api.o1.exchange'],
  'opensea': ['api.opensea.io', 'opensea.io'],
  'printr': ['api-preview.printr.money', 'app.printr.money', 'printr.money'],
  'uniswap': ['liquidity.api.uniswap.org', 'trade-api.gateway.uniswap.org'],
  'venice': ['api.venice.ai', 'outerface.venice.ai'],
  'virtuals': ['mcp.acp.virtuals.io'],
  'yo': [],
};

/** Every allowlisted host, flattened. */
export const BASE_MCP_ALL_PLUGIN_HOSTS_V1: readonly string[] = Object.freeze(
  [...new Set(Object.values(BASE_MCP_PLUGIN_HOSTS_V1).flat())].sort(),
);
