// GENERATED by scripts/refreshBaseMcpPluginCatalogue.mts — do not edit by hand.
//
// The native Base MCP plugins, read from the frontmatter of the specs Base
// publishes at github.com/base/skills. These are the same files Claude and
// ChatGPT load, so this is exactly the catalogue those clients see.
//
// `hosts` is each spec's own `requires.allowlist` — what Base declares the
// plugin calls — not every URL its documentation happens to mention.
//
// Committed rather than fetched: an allowlist that refreshes itself from the
// network is one nobody reviews, and an outage at the source would silently
// empty or widen it. Every change to this file arrives in a diff.
//
// Regenerated 2026-08-09.

export interface BaseMcpPluginSpecV1 {
  /** Spec filename without the extension, e.g. `o1-exchange`. */
  id: string;
  title: string;
  summary: string;
  version: string;
  /** `http-api` | `cli-only` | `hybrid` | `semantic-base-tool` | `unknown`. */
  integration: string;
  chains: readonly string[];
  tags: readonly string[];
  /** Base’s own risk labels: slippage, liquidation, irreversible, pii… */
  risk: readonly string[];
  auth: string;
  /** `none` | `optional` | `required` | `bash` | `unknown`. */
  shell: string;
  /** Declared HTTP hosts. Empty means the plugin calls none. */
  hosts: readonly string[];
  /** A separate MCP server the plugin needs, if it names one. */
  externalMcpHost: string | null;
  cliPackage: string | null;
}

export const BASE_MCP_PLUGIN_CATALOGUE_V1: readonly BaseMcpPluginSpecV1[] = [
  {
    id: 'aerodrome',
    title: 'Aerodrome Plugin',
    summary: 'Swap, provide liquidity, stake, and claim rewards on Aerodrome.',
    version: '0.2.0',
    integration: 'cli-only',
    chains: ['base'],
    tags: ['dex', 'swap', 'liquidity', 'staking'],
    risk: ['slippage'],
    auth: 'none',
    shell: 'required',
    hosts: [],
    externalMcpHost: null,
    cliPackage: 'uvx --from git+https://github.com/velodrome-finance/sugar-sdk.git@v0.4.0 sugar',
  },
  {
    id: 'avantis',
    title: 'Avantis Plugin',
    summary: 'Open and manage leveraged perpetual-futures positions on Avantis.',
    version: '0.2.0',
    integration: 'hybrid',
    chains: ['base'],
    tags: ['perps', 'leverage', 'trading', 'derivatives'],
    risk: ['liquidation', 'slippage', 'irreversible'],
    auth: 'none',
    shell: 'optional',
    hosts: ['api.avantisfi.com', 'core.avantisfi.com', 'data.avantisfi.com'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'balancer',
    title: 'Balancer Plugin',
    summary: 'Swaps and liquidity on Balancer through a shell: read pools/quotes from the Balancer API, build calldata with the Balancer SDK, submit via send_calls. CLI-only — requires terminal access; unsupported on chat-only surfaces.',
    version: '0.1.0',
    integration: 'cli-only',
    chains: ['base', 'ethereum', 'arbitrum', 'optimism', 'avalanche'],
    tags: ['dex', 'swap', 'liquidity', 'yield'],
    risk: ['slippage', 'low-liquidity'],
    auth: 'none',
    shell: 'required',
    hosts: [],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'bankr',
    title: 'Bankr Plugin',
    summary: 'Discover and buy newly launched tokens on Bankr.',
    version: '0.2.0',
    integration: 'http-api',
    chains: ['base'],
    tags: ['token-launches', 'trading', 'memecoins', 'discovery'],
    risk: ['low-liquidity', 'irreversible'],
    auth: 'none',
    shell: 'none',
    hosts: ['api.bankr.bot'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'bitrefill',
    title: 'Bitrefill Plugin',
    summary: 'Shop 1,500+ brands in 180+ countries — Amazon, Steam, Netflix, mobile top-ups, and travel eSIMs — paid with USDC on Base. Your agent searches, checks out, and delivers gift-card codes and eSIM details in chat. No Bitrefill account required.',
    version: '0.4.0',
    integration: 'hybrid',
    chains: ['base'],
    tags: ['agent-commerce', 'gift-cards', 'esim', 'mobile-topup', 'payments'],
    risk: ['pii', 'irreversible'],
    auth: 'siwe-jwt',
    shell: 'optional',
    hosts: ['api.bitrefill.com'],
    externalMcpHost: 'api.bitrefill.com',
    cliPackage: '@bitrefill/cli@latest',
  },
  {
    id: 'brickken',
    title: 'Brickken Plugin',
    summary: 'ERC-8004 identity, reputation, and agent-token operations through Brickken with Base MCP x402 approval.',
    version: '0.2.0',
    integration: 'hybrid',
    chains: ['base', 'base-sepolia'],
    tags: ['ai-agents', 'agent-commerce', 'token-launches'],
    risk: ['irreversible', 'pii'],
    auth: 'none',
    shell: 'optional',
    hosts: ['mcp.brickken.com'],
    externalMcpHost: null,
    cliPackage: 'npx brickken-cli',
  },
  {
    id: 'clawnch',
    title: 'Clawnch Plugin',
    summary: 'Token-launch discovery (recent + top-by-volume) and non-custodial token launches on Clawnch via HTTP API → swap / send_calls on Base.',
    version: '0.1.0',
    integration: 'http-api',
    chains: ['base'],
    tags: ['token-launches', 'memecoins', 'discovery', 'trading'],
    risk: ['low-liquidity', 'slippage', 'irreversible'],
    auth: 'none',
    shell: 'none',
    hosts: ['www.clawn.ch'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'flaunch',
    title: 'Flaunch Plugin',
    summary: 'Prepare Flaunch launches through mcp.flaunch.gg and submit them with Base MCP send_calls; discover and swap deployed tokens through Base MCP.',
    version: '0.2.0',
    integration: 'http-api',
    chains: ['base'],
    tags: ['token-launches', 'memecoins', 'discovery', 'swap'],
    risk: ['low-liquidity', 'slippage', 'irreversible'],
    auth: 'unknown',
    shell: 'unknown',
    hosts: ['mcp.flaunch.gg'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'gmgn',
    title: 'GMGN Plugin',
    summary: 'Token swap quotes and on-chain market intelligence for Base via GMGN API. Requires shell to generate auth parameters; returns unsigned calldata for send_calls execution.',
    version: '1.0.0',
    integration: 'cli-only',
    chains: ['base'],
    tags: ['swap', 'trading', 'discovery'],
    risk: ['slippage', 'low-liquidity'],
    auth: 'api-key',
    shell: 'bash',
    hosts: ['openapi.gmgn.ai'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'hydrex',
    title: 'Hydrex Plugin',
    summary: 'Swapping and concentrated-liquidity on Hydrex via local prepare server → send_calls on Base.',
    version: '0.2.0',
    integration: 'http-api',
    chains: ['base'],
    tags: ['dex', 'swap', 'liquidity', 'yield'],
    risk: ['slippage', 'irreversible'],
    auth: 'none',
    shell: 'none',
    hosts: ['hydrex-agent.com'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'kyberswap',
    title: 'KyberSwap Plugin',
    summary: 'DEX aggregation on KyberSwap via HTTP API → send_calls across 7 chains, best-rate routing through 50+ liquidity sources.',
    version: '0.2.0',
    integration: 'http-api',
    chains: ['base', 'ethereum', 'arbitrum', 'optimism', 'polygon', 'bsc', 'avalanche'],
    tags: ['dex', 'swap', 'liquidity'],
    risk: ['slippage'],
    auth: 'none',
    shell: 'none',
    hosts: ['aggregator-api.kyberswap.com', 'token-api.kyberswap.com'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'moonwell',
    title: 'Moonwell Plugin',
    summary: 'Lend, borrow, and manage positions on Moonwell.',
    version: '0.2.0',
    integration: 'http-api',
    chains: ['base', 'optimism'],
    tags: ['lending', 'borrowing', 'yield'],
    risk: ['liquidation'],
    auth: 'none',
    shell: 'none',
    hosts: ['api.moonwell.fi'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'morpho',
    title: 'Morpho Plugin',
    summary: 'Lend, borrow, and manage vault or market positions on Morpho.',
    version: '0.3.0',
    integration: 'hybrid',
    chains: ['base'],
    tags: ['lending', 'borrowing', 'vaults', 'yield'],
    risk: ['liquidation'],
    auth: 'none',
    shell: 'optional',
    hosts: ['mcp.morpho.org'],
    externalMcpHost: null,
    cliPackage: 'npx @morpho-org/cli@latest',
  },
  {
    id: 'o1-exchange',
    title: 'o1.exchange Plugin',
    summary: 'Token trading on o1.exchange via HTTP API → send_calls on Base, and BSC.',
    version: '0.3.0',
    integration: 'http-api',
    chains: ['base', 'bsc'],
    tags: ['trading', 'swap', 'dex'],
    risk: ['slippage', 'irreversible', 'low-liquidity'],
    auth: 'none',
    shell: 'none',
    hosts: ['api.o1.exchange'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'opensea',
    title: 'OpenSea Plugin',
    summary: 'NFT marketplace trading, token swaps, and drops/minting via OpenSea REST API + CLI → send_calls on Ethereum, Base, Polygon, Arbitrum, Optimism, and Avalanche.',
    version: '0.4.0',
    integration: 'hybrid',
    chains: ['ethereum', 'base', 'polygon', 'arbitrum', 'optimism', 'avalanche'],
    tags: ['nft', 'marketplace', 'swap', 'drops', 'trading'],
    risk: ['slippage', 'irreversible'],
    auth: 'api-key',
    shell: 'optional',
    hosts: ['api.opensea.io'],
    externalMcpHost: null,
    cliPackage: 'npx @opensea/cli@latest',
  },
  {
    id: 'printr',
    title: 'Printr Plugin',
    summary: 'Launch cross-chain tokens on Printr via its public HTTP API → submit the unsigned creation calldata through Base MCP send_calls.',
    version: '0.2.0',
    integration: 'http-api',
    chains: ['base', 'arbitrum', 'optimism', 'polygon', 'bsc', 'avalanche', 'ethereum'],
    tags: ['token-launches', 'memecoins', 'trading'],
    risk: ['low-liquidity', 'irreversible'],
    auth: 'none',
    shell: 'none',
    hosts: ['api-preview.printr.money'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'uniswap',
    title: 'Uniswap Plugin',
    summary: 'Swap tokens and manage liquidity positions on Uniswap.',
    version: '0.2.0',
    integration: 'http-api',
    chains: ['base'],
    tags: ['dex', 'swap', 'liquidity'],
    risk: ['slippage'],
    auth: 'api-key',
    shell: 'none',
    hosts: ['liquidity.api.uniswap.org', 'trade-api.gateway.uniswap.org'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'venice',
    title: 'Venice AI Plugin',
    summary: 'Private AI inference through the Venice API, with optional Base x402 wallet funding via Base MCP.',
    version: '0.2.0',
    integration: 'hybrid',
    chains: ['base'],
    tags: ['ai-inference', 'media-generation', 'x402-payments'],
    risk: ['pii', 'irreversible'],
    auth: 'siwe-jwt',
    shell: 'none',
    hosts: ['api.venice.ai'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'virtuals',
    title: 'Virtuals Plugin',
    summary: 'Create and manage Virtuals AI agents, cards, and email.',
    version: '0.3.0',
    integration: 'http-api',
    chains: [],
    tags: ['ai-agents', 'agent-commerce', 'payment-cards', 'email'],
    risk: ['pii'],
    auth: 'siwe-jwt',
    shell: 'none',
    hosts: ['mcp.acp.virtuals.io'],
    externalMcpHost: null,
    cliPackage: null,
  },
  {
    id: 'yo',
    title: 'YO Protocol Plugin',
    summary: 'View YO vaults, check positions, deposit, and request redeem on YO\'s ERC-4626 yield vaults — fully on-chain reads via chain_rpc_request and unsigned calldata to send_calls on Base, Ethereum, and Arbitrum.',
    version: '0.1.0',
    integration: 'semantic-base-tool',
    chains: ['base', 'ethereum', 'arbitrum'],
    tags: ['yield', 'vaults'],
    risk: ['slippage', 'irreversible'],
    auth: 'none',
    shell: 'none',
    hosts: [],
    externalMcpHost: null,
    cliPackage: null,
  },
];

/** The date the catalogue above was read from Base. */
export const BASE_MCP_CATALOGUE_GENERATED_AT_V1 = '2026-08-09';

/** The HTTP scope per plugin, derived from the catalogue so there is one source. */
export const BASE_MCP_PLUGIN_HOSTS_V1: Readonly<Record<string, readonly string[]>> = Object.freeze(
  Object.fromEntries(BASE_MCP_PLUGIN_CATALOGUE_V1.map((plugin) => [plugin.id, plugin.hosts])),
);

/** Every allowlisted host, flattened. */
export const BASE_MCP_ALL_PLUGIN_HOSTS_V1: readonly string[] = Object.freeze(
  [...new Set(BASE_MCP_PLUGIN_CATALOGUE_V1.flatMap((plugin) => plugin.hosts))].sort(),
);
