// ---------------------------------------------------------------------------
// Regenerate the Base MCP plugin host allowlist from Base's published specs.
//
// Run by hand, never at request time:
//
//   node --import tsx scripts/refreshBaseMcpPluginHosts.mts
//
// The output is COMMITTED. That is the point: the set of hosts Miorail may
// reach is a security boundary, and a boundary that refreshes itself from the
// network is one nobody reviews. Fetching it live would also mean an outage —
// or a compromise — at github.com silently widening or emptying the allowlist.
// Generating into a file puts every change in a diff someone has to read.
//
// The specs are the same markdown the Base MCP skill loads in Claude, ChatGPT
// and Cursor, so the hosts here are exactly the hosts those clients reach.
// ---------------------------------------------------------------------------

const SPEC_BASE_V1 =
  'https://raw.githubusercontent.com/base/skills/master/skills/base-mcp/plugins';

/** The native plugins Base ships with the skill, from /agents/plugins/native. */
const PLUGINS_V1 = [
  'aerodrome', 'avantis', 'balancer', 'bankr', 'bitrefill', 'brickken',
  'clawnch', 'flaunch', 'gmgn', 'hydrex', 'kyberswap', 'moonwell', 'morpho',
  'o1-exchange', 'opensea', 'printr', 'uniswap', 'venice', 'virtuals', 'yo',
] as const;

/**
 * Hosts that must never enter the allowlist even if a spec mentions them.
 *
 * Every spec links to its own source on GitHub, and several show example
 * output containing explorer or docs links. None of those are endpoints a
 * plugin calls, and an allowlist is only as good as what it leaves out.
 */
const NEVER_ALLOWLIST_V1 = new Set([
  'github.com',
  'raw.githubusercontent.com',
  'docs.base.org',
  'basescan.org',
  'etherscan.io',
  'example.com',
  'localhost',
  // Reached through the MCP client, not through plugin HTTP.
  'mcp.base.org',
  // An RPC endpoint is not a plugin API, and ours is configured elsewhere.
  'mainnet.base.org',
  'sepolia.base.org',
]);

/**
 * Hosts a spec links to but never calls.
 *
 * Plugin specs are documentation as much as instructions: they link the
 * protocol's Discord, its X account, its docs site, and images in example
 * output. Extracting every URL and calling the result an allowlist would put
 * `discord.gg` and `x.com` on the list of hosts Miorail may reach — which
 * turns the boundary into decoration.
 */
const NOT_AN_API_HOST_V1 = [
  'x.com', 'twitter.com', 'pbs.twimg.com', 'discord.gg', 'discord.com',
  't.me', 'telegram.me', 'whop.com', 'youtube.com', 'medium.com',
  'linktr.ee', 'warpcast.com', 'farcaster.xyz',
];

/** `docs.*` and `help.*` are reference sites, never endpoints. */
const DOC_SUBDOMAIN_V1 = /^(docs|help|support|blog|www\.docs)\./;

function isApiHost(host: string): boolean {
  if (NEVER_ALLOWLIST_V1.has(host)) return false;
  if (NOT_AN_API_HOST_V1.includes(host)) return false;
  if (DOC_SUBDOMAIN_V1.test(host)) return false;
  return true;
}

const HOST_PATTERN_V1 = /https?:\/\/([a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+)/gi;

async function fetchSpec(plugin: string): Promise<string | null> {
  const response = await fetch(`${SPEC_BASE_V1}/${plugin}.md`, {
    signal: AbortSignal.timeout(20_000),
  });
  if (!response.ok) return null;
  return response.text();
}

async function main(): Promise<void> {
  const byPlugin = new Map<string, string[]>();
  const missing: string[] = [];

  for (const plugin of PLUGINS_V1) {
    const spec = await fetchSpec(plugin);
    if (spec === null) {
      missing.push(plugin);
      continue;
    }
    const hosts = new Set<string>();
    for (const match of spec.matchAll(HOST_PATTERN_V1)) {
      const host = (match[1] ?? '').toLowerCase();
      if (!host || !isApiHost(host)) continue;
      hosts.add(host);
    }
    byPlugin.set(plugin, [...hosts].sort());
  }

  const lines: string[] = [
    '// GENERATED by scripts/refreshBaseMcpPluginHosts.mts — do not edit by hand.',
    '//',
    '// The hosts each native Base MCP plugin reaches, taken from the specs Base',
    "// publishes at github.com/base/skills. These are the same files Claude and",
    '// ChatGPT load, so this list is exactly what those clients can reach.',
    '//',
    '// Committed rather than fetched: an allowlist that refreshes itself from the',
    '// network is one nobody reviews, and an outage at the source would silently',
    '// empty or widen it. Every change to this file arrives in a diff.',
    '//',
    `// Regenerated ${new Date().toISOString().slice(0, 10)}.`,
    '',
    'export const BASE_MCP_PLUGIN_HOSTS_V1: Readonly<Record<string, readonly string[]>> = {',
  ];
  for (const [plugin, hosts] of [...byPlugin].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  '${plugin}': [${hosts.map((host) => `'${host}'`).join(', ')}],`);
  }
  lines.push('};', '');
  lines.push('/** Every allowlisted host, flattened. */');
  lines.push('export const BASE_MCP_ALL_PLUGIN_HOSTS_V1: readonly string[] = Object.freeze(');
  lines.push('  [...new Set(Object.values(BASE_MCP_PLUGIN_HOSTS_V1).flat())].sort(),');
  lines.push(');');
  lines.push('');

  const target = new URL('../lib/security/src/baseMcpPluginHosts.generated.ts', import.meta.url);
  const { writeFile } = await import('node:fs/promises');
  await writeFile(target, lines.join('\n'), 'utf8');

  const total = new Set([...byPlugin.values()].flat()).size;
  console.log(`Wrote ${byPlugin.size} plugins, ${total} distinct hosts.`);
  if (missing.length > 0) {
    // Named, never silently skipped: a plugin whose spec did not download is a
    // plugin that will not work, and the operator has to know which.
    console.log(`Spec not downloaded (left OUT of the allowlist): ${missing.join(', ')}`);
  }
}

await main();
