// ---------------------------------------------------------------------------
// The Base MCP plugin catalogue — the thing this screen was named after and
// did not contain.
//
// Extensions shipped with one card headed "Base MCP plugins" that listed
// `get_portfolio`, `send`, `swap` and a dozen others. Those are Base MCP's
// CORE TOOLS: the fifteen calls the server itself exposes. The plugins are a
// different layer — twenty markdown specifications Base publishes, each one a
// protocol (Uniswap, Morpho, OpenSea, Aerodrome…) with its own hosts, its own
// auth and its own risks. Not one of them appeared. The heading was a promise
// the card never kept, and a user who opened the page to see what was
// available saw the plumbing instead.
//
// Two facts decide how this renders.
//
//   * The catalogue is COMMITTED, because it carries the host allowlist.
//     A boundary that refreshes itself from the network is one nobody reviews.
//   * A committed catalogue goes stale, and staleness that nobody can see is
//     indistinguishable from being current. So the drift line is not
//     decoration: it is the difference between "Base publishes twenty and we
//     know all twenty" and "we have no idea, and this list may be behind".
//
// The three drift states stay three. A check that could not run is `unchecked`
// — never `in_sync`, never "Base removed everything". Our own outage does not
// get to wear Base's name.
// ---------------------------------------------------------------------------

export interface BaseMcpPluginRowV1 {
  id: string;
  title: string;
  summary: string;
  version: string;
  integration: string;
  chains: readonly string[];
  tags: readonly string[];
  /** Base's own risk labels: slippage, liquidation, irreversible, pii… */
  risk: readonly string[];
  auth: string;
  shell: string;
  hosts: readonly string[];
  externalMcpHost: string | null;
  cliPackage: string | null;
  productSurface: 'routes' | 'extensions';
  lifecycleStage: 'documented' | 'manifested' | 'adapter' | 'scored' | 'proven';
  examples: readonly {
    id: string;
    prompt: string;
    surface: 'read' | 'action' | 'routable';
    disposition: 'read_in_extensions' | 'handoff_to_routes' | 'handoff_to_provider_ui' | 'typed_x402_required' | 'adapter_required';
  }[];
}

export interface BaseMcpPluginDriftRowV1 {
  status: 'in_sync' | 'drifted' | 'unchecked';
  knownCount: number;
  publishedCount: number | null;
  added: readonly string[];
  removed: readonly string[];
  checkedAt: string | null;
  reason: string | null;
}

export interface BaseMcpPluginsModelV1 {
  loading: boolean;
  plugins: readonly BaseMcpPluginRowV1[];
  drift: BaseMcpPluginDriftRowV1 | null;
  /** The date the committed catalogue was read from Base. */
  generatedAt: string | null;
  /** Rendered INSTEAD of the list. Never alongside a partial one. */
  unavailableReason: string | null;
  /** Selecting an example only fills the console. It never executes it. */
  onSelectPrompt?: (prompt: string) => void;
}

/** How a plugin would be reached from here — which is not the same question as
 * what it can do, and is the one that decides whether it works in Miorail. */
export type BaseMcpPluginReachV1 = 'http' | 'base_tools' | 'external_mcp' | 'shell_required';

export function baseMcpPluginReachV1(plugin: BaseMcpPluginRowV1): BaseMcpPluginReachV1 {
  // Shell first, and deliberately before hosts: GMGN declares an API host and
  // still cannot run here, because its auth parameters are generated by shell
  // commands. Listing it as reachable because it named a host would be wrong
  // in the one direction that matters.
  if (plugin.integration === 'cli-only' || plugin.shell === 'required' || plugin.shell === 'bash') {
    return 'shell_required';
  }
  if (plugin.hosts.length > 0) return 'http';
  if (plugin.externalMcpHost) return 'external_mcp';
  return 'base_tools';
}

export const BASE_MCP_PLUGIN_REACH_COPY_V1: Readonly<Record<BaseMcpPluginReachV1, string>> = {
  http:
    'Reachable from Miorail. Requests go to the hosts the plugin itself declares, and anything it prepares is still approved in your Base Account.',
  base_tools:
    'Uses Base MCP’s own tools and the chain directly — no API host of its own.',
  external_mcp:
    'Needs a separate MCP server. Not connected here.',
  shell_required:
    'Runs through a terminal. Miorail gives no shell, so this one works in a CLI client and not on this surface.',
};

const REACH_LABEL_V1: Readonly<Record<BaseMcpPluginReachV1, string>> = {
  http: 'http api',
  base_tools: 'base tools',
  external_mcp: 'external mcp',
  shell_required: 'shell required',
};

/** console.css gives `.pill` exactly four tones — br, g, a, n. */
const REACH_TONE_V1: Readonly<Record<BaseMcpPluginReachV1, string>> = {
  http: 'g',
  base_tools: 'br',
  external_mcp: 'a',
  shell_required: 'n',
};

const REACH_ORDER_V1: readonly BaseMcpPluginReachV1[] = [
  'http',
  'base_tools',
  'external_mcp',
  'shell_required',
];

export function groupBaseMcpPluginsV1(
  plugins: readonly BaseMcpPluginRowV1[],
): { reach: BaseMcpPluginReachV1; plugins: BaseMcpPluginRowV1[] }[] {
  return REACH_ORDER_V1.map((reach) => ({
    reach,
    plugins: plugins
      .filter((plugin) => baseMcpPluginReachV1(plugin) === reach)
      .sort((left, right) => left.id.localeCompare(right.id)),
  })).filter((group) => group.plugins.length > 0);
}

/**
 * The drift sentence.
 *
 * Written so that the honest answer to "is this list current?" is legible in
 * one line, including when the answer is "nobody could tell".
 */
export function baseMcpPluginDriftCopyV1(
  drift: BaseMcpPluginDriftRowV1 | null,
  generatedAt: string | null,
): string {
  const read = generatedAt ? ` Catalogue read from Base on ${generatedAt}.` : '';
  if (!drift) return `Showing the plugins Miorail has on file.${read}`;

  if (drift.status === 'in_sync') {
    return `Base publishes ${drift.publishedCount ?? drift.knownCount} plugins and Miorail has all of them.${read}`;
  }
  if (drift.status === 'drifted') {
    const parts: string[] = [];
    if (drift.added.length > 0) {
      parts.push(`new at Base and not here yet: ${drift.added.join(', ')}`);
    }
    if (drift.removed.length > 0) {
      parts.push(`here but no longer published by Base: ${drift.removed.join(', ')}`);
    }
    return `Base publishes ${drift.publishedCount ?? '—'} plugins, Miorail has ${drift.knownCount} — ${parts.join('; ')}.${read}`;
  }
  const why =
    drift.reason === 'check_disabled'
      ? 'The check against Base’s list is switched off on this server'
      : 'Base’s list could not be read just now';
  return `${why}, so this may be behind. Showing the ${drift.knownCount} plugins Miorail has on file.${read}`;
}

const DRIFT_TONE_V1: Readonly<Record<BaseMcpPluginDriftRowV1['status'], string>> = {
  in_sync: 'g',
  drifted: 'a',
  unchecked: 'n',
};

const DRIFT_LABEL_V1: Readonly<Record<BaseMcpPluginDriftRowV1['status'], string>> = {
  in_sync: 'in sync with Base',
  drifted: 'behind Base',
  unchecked: 'not checked',
};

/** `base · ethereum · arbitrum`, or a stated absence. */
function chainsLabelV1(chains: readonly string[]): string {
  return chains.length > 0 ? chains.join(' · ') : 'no chain stated';
}

/**
 * The plugin's own description, cut to one line.
 *
 * Base writes these at wildly different lengths — Uniswap's is eight words,
 * Bitrefill's is fifty-one — and rendering them whole turned twenty plugins
 * into a wall of prose with no two rows the same height. A list you cannot
 * scan is a list nobody reads. The full text is one click away at the spec;
 * what this surface owes the reader is which plugins exist and what each one
 * touches.
 */
export function baseMcpPluginSummaryLineV1(summary: string, max = 96): string {
  const flat = summary.replace(/\s+/g, ' ').trim();
  if (flat.length <= max) return flat;
  // Cut on a word boundary so the ellipsis does not land mid-word.
  const cut = flat.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

/** The second line of a plugin row: what it touches and what it costs to be
 * wrong about it. Base's own risk labels, not ours. */
export function baseMcpPluginMetaLineV1(plugin: BaseMcpPluginRowV1): string {
  const parts = [chainsLabelV1(plugin.chains)];
  if (plugin.auth && plugin.auth !== 'none' && plugin.auth !== 'unknown') {
    parts.push(`auth: ${plugin.auth}`);
  }
  if (plugin.risk.length > 0) parts.push(`risk: ${plugin.risk.join(', ')}`);
  return parts.join(' · ');
}

/** The right-hand column: where the plugin actually goes. One host, plus a
 * count when there are more — three full hostnames in a right-aligned mono
 * column is the widest, least readable thing on the card. */
export function baseMcpPluginHostsLabelV1(hosts: readonly string[]): string {
  if (hosts.length === 0) return '—';
  if (hosts.length === 1) return hosts[0]!;
  return `${hosts[0]} +${hosts.length - 1}`;
}

export function BaseMcpPluginsCard(model: BaseMcpPluginsModelV1) {
  const groups = groupBaseMcpPluginsV1(model.plugins);
  const drift = model.drift;

  return (
    <div className="rp">
      <div className="rph">
        <b>Base MCP plugins</b>
        <span className="rt mono">{model.plugins.length || '—'}</span>
      </div>
      <div className="rpb">
        {drift && (
          <div className="qrow">
            <span className={`pill ${DRIFT_TONE_V1[drift.status]}`}>{DRIFT_LABEL_V1[drift.status]}</span>
            <span className="v mono">
              {drift.publishedCount === null ? `${drift.knownCount}` : `${drift.knownCount}/${drift.publishedCount}`}
            </span>
          </div>
        )}
        <p className="lnote">{baseMcpPluginDriftCopyV1(drift, model.generatedAt)}</p>

        {model.loading && model.plugins.length === 0 ? (
          <p className="empty">Reading the plugin catalogue…</p>
        ) : model.unavailableReason ? (
          <p className="empty">{model.unavailableReason}</p>
        ) : groups.length === 0 ? (
          <p className="empty">No plugins on file.</p>
        ) : (
          groups.map((group) => (
            <div key={group.reach}>
              <div className="qrow">
                <span className={`pill ${REACH_TONE_V1[group.reach]}`}>{REACH_LABEL_V1[group.reach]}</span>
                <span className="v mono">{group.plugins.length}</span>
              </div>
              <p className="lnote">{BASE_MCP_PLUGIN_REACH_COPY_V1[group.reach]}</p>
              {group.plugins.map((plugin) => (
                // Three lines each, the same three every time. Uniform rows
                // are what make twenty of anything scannable; variable ones
                // read as a paragraph that happens to contain names.
                <div key={plugin.id}>
                  <div className="qrow">
                    <span className="mono">{plugin.id}</span>
                    <span className="v mono" title={plugin.hosts.join(' · ')}>
                      {baseMcpPluginHostsLabelV1(plugin.hosts)}
                    </span>
                  </div>
                  <p className="lnote">{baseMcpPluginSummaryLineV1(plugin.summary || plugin.title)}</p>
                  <p className="lnote">{baseMcpPluginMetaLineV1(plugin)}</p>
                  <p className="lnote">
                    Owner: <span className="mono">{plugin.productSurface === 'routes' ? 'Routes AI' : 'Base MCP Extensions'}</span>
                    {' · '}stage: <span className="mono">{plugin.lifecycleStage}</span>
                  </p>
                  <details>
                    <summary className="lnote">Example questions ({plugin.examples.length})</summary>
                    <div className="ctarow">
                      {plugin.examples.map((example) => (
                        <button
                          key={example.id}
                          type="button"
                          className="btn sec"
                          disabled={!model.onSelectPrompt}
                          title={`${example.surface} · ${example.disposition.replace(/_/g, ' ')}`}
                          onClick={() => model.onSelectPrompt?.(example.prompt)}
                        >
                          {example.prompt}
                        </button>
                      ))}
                    </div>
                  </details>
                </div>
              ))}
            </div>
          ))
        )}

        <p className="lnote">
          Plugins are built by third parties. Base does not operate, endorse or audit them, and
          Miorail does not either — a plugin reaches only the hosts its own spec declares, and every
          transaction is approved in your Base Account. Adding a new plugin here is a reviewed
          change, which is why the line above tells you when Base is ahead.
        </p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// The right rail for the Base MCP AI surface.
//
// The column was empty while the page it sits beside carried three stacked
// cards and a 20-row catalogue in one scrolling column. Everything here is
// already loaded — none of it costs a request — and all of it answers the
// question a reader has while looking at that catalogue: what am I connected
// to, and how much of this can actually run.
// ---------------------------------------------------------------------------

export interface BaseMcpRailModelV1 {
  /** From the live tool probe. Null before it has answered once. */
  connection: 'connected' | 'needs_reauth' | 'unreachable' | 'degraded' | null;
  enabled: boolean;
  endpointHost: string | null;
  /** Live tool counts by what each one is allowed to do. */
  toolCounts: { readOnly: number; userConfirmed: number; forbidden: number; unknown: number } | null;
  routingCounts?: {
    read: number;
    action: number;
    routable: number;
    blocked: number;
    releasedActions: number;
  } | null;
  plugins: readonly BaseMcpPluginRowV1[];
  drift: BaseMcpPluginDriftRowV1 | null;
  generatedAt: string | null;
}

const CONNECTION_TONE_V1: Readonly<Record<string, string>> = {
  connected: 'g',
  degraded: 'a',
  needs_reauth: 'a',
  unreachable: 'n',
};

export function BaseMcpSummaryRail(model: BaseMcpRailModelV1) {
  const groups = groupBaseMcpPluginsV1(model.plugins);
  const counts = model.toolCounts;
  const routing = model.routingCounts;

  return (
    <>
      <div className="rp">
        <div className="rph">
          Base MCP
          {model.endpointHost && <span className="rt mono">{model.endpointHost}</span>}
        </div>
        <div className="rpb">
          <div className="qrow">
            <span className={`pill ${model.connection ? CONNECTION_TONE_V1[model.connection] ?? 'n' : 'n'}`}>
              {model.enabled ? (model.connection ?? 'not connected').replace(/_/g, ' ') : 'switched off'}
            </span>
            <span className="v mono">{counts ? counts.readOnly + counts.userConfirmed + counts.forbidden + counts.unknown : '—'}</span>
          </div>
          {counts ? (
            <>
              <div className="qrow">
                <span>Readable</span>
                <span className="v mono">{counts.readOnly}</span>
              </div>
              <div className="qrow">
                <span>Needs your approval</span>
                <span className="v mono">{counts.userConfirmed}</span>
              </div>
              <div className="qrow">
                <span>Not callable here</span>
                <span className="v mono">{counts.forbidden + counts.unknown}</span>
              </div>
              <p className="lnote">
                The console can read and act. {routing
                  ? `${routing.releasedActions}/${routing.action} typed ACTION tools are released; ${routing.routable} ROUTABLE tools hand off to Routes AI; ${routing.blocked} still need an adapter or remain forbidden.`
                  : 'Each write still needs a typed adapter and your Base Account approval.'}
              </p>
            </>
          ) : (
            <p className="empty">The tool list has not been read yet.</p>
          )}
        </div>
      </div>

      <div className="rp">
        <div className="rph">
          Plugins
          <span className="rt mono">{model.plugins.length || '—'}</span>
        </div>
        <div className="rpb">
          {groups.length === 0 ? (
            <p className="empty">No catalogue loaded.</p>
          ) : (
            groups.map((group) => (
              <div className="qrow" key={group.reach}>
                <span>{REACH_LABEL_V1[group.reach]}</span>
                <span className="v mono">{group.plugins.length}</span>
              </div>
            ))
          )}
          <p className="lnote">{baseMcpPluginDriftCopyV1(model.drift, model.generatedAt)}</p>
        </div>
      </div>
    </>
  );
}
